[package]
name = "disksec"
description = "Storage drive firmware security assessment"
version = "0.2.0"
repository = "https://github.com/trulycrisp/disksec"
keywords = ["drive", "disk", "storage", "security", "firmware"]
categories = ["command-line-utilities", "hardware-support"]
edition = "2024"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
env_logger = { version = "0.11.10", features = ["color"] }
libc = "0.2.183"
log = "0.4.29"

[lints.rust]
missing_docs = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_docs_in_private_items = "warn"
similar_names = "allow"
struct_excessive_bools = "allow"
