imports_granularity = "Crate"
group_imports = "StdExternalCrate"

hex_literal_case = "Upper"
float_literal_trailing_zero = "Always"

wrap_comments = true
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true

format_strings = true
format_macro_matchers = true

use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true

condense_wildcard_suffixes = true
reorder_impl_items = true